use std::time::Duration;

use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value, json};

use super::config::StudioStudConfig;

pub const PAGES_BASE: &str = "https://tyleradams2002.github.io/studio-stud";

/// Ed25519 public key (32 bytes hex) embedded at build time from `secrets/channel-signing.pub`.
/// All-zeros = signing disabled (skip verification). Generated by `scripts/keygen.ps1`.
pub const MANIFEST_VERIFY_PUBLIC_KEY_HEX: &str =
    include_str!("../../secrets/channel-signing.pub");

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Channel {
    Release,
    Beta,
    Dev,
}

impl Channel {
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "beta" => Channel::Beta,
            "dev" | "development" => Channel::Dev,
            _ => Channel::Release,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Channel::Release => "release",
            Channel::Beta => "beta",
            Channel::Dev => "dev",
        }
    }

    pub fn manifest_url(self) -> String {
        match self {
            Channel::Release => format!("{PAGES_BASE}/latest.json"),
            Channel::Beta => format!("{PAGES_BASE}/beta/latest.json"),
            Channel::Dev => format!("{PAGES_BASE}/dev/latest.json"),
        }
    }

    pub fn is_encrypted(self) -> bool {
        !matches!(self, Channel::Release)
    }
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelManifest {
    pub daemon_version: String,
    pub plugin_version: String,
    pub protocol_version: Option<i64>,
    pub binary_url: Option<String>,
    pub plugin_url: Option<String>,
    pub setup_url: Option<String>,
    pub setup_enc_url: Option<String>,
    #[serde(default)]
    pub bundle_url: Option<String>,
    #[serde(default)]
    pub bundle_enc_url: Option<String>,
    #[serde(default)]
    pub channel_sequence: u64,
    pub signature: Option<String>,
}

/// Walk the fallback chain until a manifest is found, so users always have a version to run.
///   Dev  → Beta → Release
///   Beta → Release
///   Release (no fallback)
///
/// Returns `(manifest, raw_json, resolved_channel)`. `resolved_channel` differs from the
/// requested channel when the requested channel has not been published yet.
pub fn fetch_manifest_with_fallback(
    channel: Channel,
) -> Result<(ChannelManifest, Value, Channel)> {
    let chain: &[Channel] = match channel {
        Channel::Dev => &[Channel::Dev, Channel::Beta, Channel::Release],
        Channel::Beta => &[Channel::Beta, Channel::Release],
        Channel::Release => &[Channel::Release],
    };
    let mut last_err = anyhow!("no channel manifest reachable");
    for &c in chain {
        match fetch_manifest(c) {
            Ok((m, raw)) => return Ok((m, raw, c)),
            Err(e) => last_err = e,
        }
    }
    Err(last_err)
}

pub fn fetch_manifest(channel: Channel) -> Result<(ChannelManifest, Value)> {
    let url = channel.manifest_url();
    let agent: ureq::Agent = ureq::Agent::config_builder()
        .timeout_global(Some(Duration::from_secs(6)))
        .build()
        .into();
    let mut resp = agent.get(&url).call().map_err(|e| anyhow!("{url}: {e}"))?;
    let text = resp
        .body_mut()
        .read_to_string()
        .map_err(|e| anyhow!("read {url}: {e}"))?;
    let raw: Value = serde_json::from_str(&text)?;
    let manifest: ChannelManifest = serde_json::from_value(raw.clone())?;
    Ok((manifest, raw))
}

pub fn verify_manifest_signature(raw: &Value, manifest: &ChannelManifest) -> Result<()> {
    use base64::{Engine as _, engine::general_purpose::STANDARD as B64};
    use ed25519_dalek::{Signature, VerifyingKey, Verifier};

    let key_hex = MANIFEST_VERIFY_PUBLIC_KEY_HEX.trim();
    // All-zeros or placeholder = signing not yet provisioned; skip check.
    if key_hex.chars().all(|c| c == '0') || key_hex.starts_with("PLACEHOLDER") {
        return Ok(());
    }

    let key_bytes = hex_decode_32(key_hex)
        .map_err(|e| anyhow!("bad embedded public key: {e}"))?;
    let verifying_key = VerifyingKey::from_bytes(&key_bytes)
        .map_err(|e| anyhow!("invalid public key: {e}"))?;

    let Some(sig_b64) = manifest.signature.as_deref() else {
        // Unsigned channel (release): nothing to verify.
        return Ok(());
    };
    let sig_bytes = B64.decode(sig_b64)
        .map_err(|e| anyhow!("bad signature base64: {e}"))?;
    let sig_arr: [u8; 64] = sig_bytes
        .try_into()
        .map_err(|_| anyhow!("signature must be 64 bytes"))?;
    let signature = Signature::from_bytes(&sig_arr);

    let canonical = canonical_manifest_bytes(raw)?;
    verifying_key
        .verify(&canonical, &signature)
        .map_err(|_| anyhow!("manifest signature verification failed"))
}

/// Canonical bytes a manifest is signed/verified over: the manifest JSON object with the
/// `signature` field removed, serialized deterministically (sorted keys via serde_json's default
/// BTreeMap-backed Map). BOTH the signer (examples/sign-manifest.rs) and the verifier call this,
/// so the byte string is identical regardless of how the published file was key-ordered.
pub fn canonical_manifest_bytes(raw: &Value) -> Result<Vec<u8>> {
    let mut obj = raw
        .as_object()
        .cloned()
        .ok_or_else(|| anyhow!("manifest is not a JSON object"))?;
    obj.remove("signature");
    Ok(serde_json::to_string(&Value::Object(obj))?.into_bytes())
}

fn hex_decode_32(s: &str) -> Result<[u8; 32]> {
    let bytes = (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16))
        .collect::<Result<Vec<u8>, _>>()
        .map_err(|e| anyhow!("hex decode: {e}"))?;
    bytes.try_into().map_err(|_| anyhow!("expected 32 bytes, got {}", s.len() / 2))
}

/// URL for the channel BUNDLE zip (plain on release, encrypted on beta/dev).
pub fn bundle_artifact_url(resolved: Channel, manifest: &ChannelManifest) -> Result<String> {
    if resolved.is_encrypted() {
        manifest
            .bundle_enc_url
            .clone()
            .ok_or_else(|| anyhow!("manifest missing bundleEncUrl for {}", resolved.as_str()))
    } else {
        manifest
            .bundle_url
            .clone()
            .ok_or_else(|| anyhow!("manifest missing bundleUrl for {}", resolved.as_str()))
    }
}

/// URL for the channel setup artifact (plain `setupUrl` or encrypted `setupEncUrl`).
pub fn setup_artifact_url(resolved: Channel, manifest: &ChannelManifest) -> Result<String> {
    if resolved.is_encrypted() {
        manifest
            .setup_enc_url
            .clone()
            .ok_or_else(|| anyhow!("manifest missing setupEncUrl for {}", resolved.as_str()))
    } else {
        manifest
            .setup_url
            .clone()
            .ok_or_else(|| anyhow!("manifest missing setupUrl for {}", resolved.as_str()))
    }
}

pub fn required_binary_url(manifest: &ChannelManifest) -> Result<String> {
    manifest
        .binary_url
        .clone()
        .ok_or_else(|| anyhow!("manifest missing binaryUrl"))
}

pub fn required_plugin_url(manifest: &ChannelManifest) -> Result<String> {
    manifest
        .plugin_url
        .clone()
        .ok_or_else(|| anyhow!("manifest missing pluginUrl"))
}

/// Whether an update should be applied for the user's channel manifest.
pub fn channel_update_available(
    on_fallback: bool,
    manifest_version: &str,
    installed: &str,
) -> bool {
    if on_fallback {
        return false;
    }
    !manifest_version.is_empty() && manifest_version != installed
}

/// Sequence-aware update check. Prefer the monotonic `channelSequence` (advances on every publish,
/// even when the semver version is unchanged). Fall back to a semver compare only when no baseline
/// sequence has been recorded yet (e.g. a just-installed machine that hasn't stored one).
pub fn channel_update_available_seq(
    on_fallback: bool,
    manifest_seq: u64,
    last_seen_seq: u64,
    manifest_version: &str,
    installed: &str,
) -> bool {
    if on_fallback {
        return false;
    }
    if last_seen_seq == 0 {
        return !manifest_version.is_empty()
            && manifest_version != installed
            && crate::update::is_newer(manifest_version, installed);
    }
    manifest_seq > last_seen_seq
}

pub fn record_channel_sequence(
    cfg: &mut StudioStudConfig,
    resolved: Channel,
    seq: u64,
) {
    cfg.last_channel_sequence
        .insert(resolved.as_str().into(), json!(seq));
}

/// When `env_sequence` is present and parses to `u64 > 0`, records it unconditionally
/// for `channel` (install-time overwrite of an existing baseline). Returns `true` when
/// recorded; `false` when absent/invalid so the caller can fall through to
/// `record_install_baseline_seq`.
pub fn record_install_sequence_from_env(
    cfg: &mut StudioStudConfig,
    channel: &str,
    env_sequence: Option<&str>,
) -> bool {
    let Some(raw) = env_sequence else {
        return false;
    };
    let Ok(seq) = raw.parse::<u64>() else {
        return false;
    };
    if seq == 0 {
        return false;
    }
    let resolved = Channel::from_str(channel);
    record_channel_sequence(cfg, resolved, seq);
    true
}

/// Best-effort install-time baseline: record the configured channel's current published
/// `channelSequence` so the NEXT publish (seq+1) triggers an update even when the semver is
/// unchanged (the headline dev workflow). No-op when a baseline already exists (repair/reinstall
/// must preserve it), when resolving onto a fallback channel, or when the manifest can't be
/// fetched/verified — offline installs simply degrade to the semver fallback in
/// `channel_update_available_seq`.
pub fn record_install_baseline_seq(cfg: &mut StudioStudConfig) {
    let requested = Channel::from_str(&cfg.channel);
    let existing = cfg
        .last_channel_sequence
        .get(requested.as_str())
        .and_then(Value::as_u64)
        .unwrap_or(0);
    if existing != 0 {
        return; // repair / reinstall: preserve the recorded baseline (and stay offline-safe)
    }
    let Ok((manifest, raw, resolved)) = fetch_manifest_with_fallback(requested) else {
        return;
    };
    if resolved != requested {
        return; // on fallback: let the real channel's first publish set the baseline
    }
    if verify_manifest_signature(&raw, &manifest).is_err() || manifest.channel_sequence == 0 {
        return;
    }
    record_channel_sequence(cfg, resolved, manifest.channel_sequence);
}

pub fn last_channel_sequence_json(cfg: &StudioStudConfig) -> Map<String, Value> {
    cfg.last_channel_sequence.clone()
}

pub fn check_anti_rollback(
    channel: Channel,
    manifest: &ChannelManifest,
    last_seen: &serde_json::Map<String, Value>,
) -> Result<()> {
    let key = channel.as_str();
    let floor = last_seen
        .get(key)
        .and_then(Value::as_u64)
        .unwrap_or(0);
    if manifest.channel_sequence < floor {
        return Err(anyhow!(
            "manifest channelSequence {} is below floor {}",
            manifest.channel_sequence,
            floor
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_manifest() -> ChannelManifest {
        ChannelManifest {
            daemon_version: "0.5.0".into(),
            plugin_version: "0.4.0".into(),
            protocol_version: Some(1),
            binary_url: Some("https://example.com/studio-stud.exe".into()),
            plugin_url: Some("https://example.com/StudioStud.plugin.lua".into()),
            setup_url: Some("https://example.com/studio-stud-setup.exe".into()),
            setup_enc_url: Some("https://example.com/beta/studio-stud-setup.exe.enc".into()),
            bundle_url: Some("https://example.com/studio-stud-bundle.zip".into()),
            bundle_enc_url: Some("https://example.com/beta/studio-stud-bundle.zip.enc".into()),
            channel_sequence: 2,
            signature: None,
        }
    }

    #[test]
    fn setup_artifact_url_release_uses_setup_url() {
        let m = sample_manifest();
        let url = setup_artifact_url(Channel::Release, &m).unwrap();
        assert_eq!(url, "https://example.com/studio-stud-setup.exe");
    }

    #[test]
    fn setup_artifact_url_beta_uses_enc_url() {
        let m = sample_manifest();
        let url = setup_artifact_url(Channel::Beta, &m).unwrap();
        assert_eq!(url, "https://example.com/beta/studio-stud-setup.exe.enc");
    }

    #[test]
    fn setup_artifact_url_missing_field_errors() {
        let mut m = sample_manifest();
        m.setup_url = None;
        assert!(setup_artifact_url(Channel::Release, &m).is_err());
    }

    #[test]
    fn bundle_artifact_url_release_uses_bundle_url() {
        let m = sample_manifest();
        let url = bundle_artifact_url(Channel::Release, &m).unwrap();
        assert_eq!(url, "https://example.com/studio-stud-bundle.zip");
    }

    #[test]
    fn bundle_artifact_url_beta_uses_enc_url() {
        let m = sample_manifest();
        let url = bundle_artifact_url(Channel::Beta, &m).unwrap();
        assert_eq!(url, "https://example.com/beta/studio-stud-bundle.zip.enc");
    }

    #[test]
    fn bundle_artifact_url_missing_field_errors() {
        let mut m = sample_manifest();
        m.bundle_url = None;
        assert!(bundle_artifact_url(Channel::Release, &m).is_err());
    }

    #[test]
    fn channel_update_available_respects_fallback_and_version() {
        assert!(!channel_update_available(true, "0.5.0", "0.4.0"));
        assert!(!channel_update_available(false, "0.4.0", "0.4.0"));
        assert!(channel_update_available(false, "0.5.0", "0.4.0"));
        assert!(channel_update_available(false, "0.4.9", "0.5.0"));
    }

    #[test]
    fn seq_trigger_fires_on_higher_sequence_same_version() {
        // baseline seq 3, published seq 4, same version => update
        assert!(channel_update_available_seq(false, 4, 3, "0.4.0", "0.4.0"));
        // no baseline yet, same version => no update (semver fallback)
        assert!(!channel_update_available_seq(false, 4, 0, "0.4.0", "0.4.0"));
        // fallback channel => never
        assert!(!channel_update_available_seq(true, 9, 1, "0.9.0", "0.4.0"));
    }

    #[test]
    fn record_channel_sequence_writes_floor() {
        let mut cfg = StudioStudConfig::default();
        record_channel_sequence(&mut cfg, Channel::Beta, 7);
        assert_eq!(cfg.last_channel_sequence["beta"], json!(7));
    }

    #[test]
    fn install_sequence_from_env_overwrites_existing_baseline() {
        let mut cfg = StudioStudConfig {
            channel: "release".into(),
            ..StudioStudConfig::default()
        };
        record_channel_sequence(&mut cfg, Channel::Release, 5);
        assert!(record_install_sequence_from_env(&mut cfg, "release", Some("42")));
        assert_eq!(cfg.last_channel_sequence["release"], json!(42));
    }

    #[test]
    fn install_sequence_from_env_absent_leaves_existing_baseline() {
        let mut cfg = StudioStudConfig {
            channel: "release".into(),
            ..StudioStudConfig::default()
        };
        record_channel_sequence(&mut cfg, Channel::Release, 5);
        assert!(!record_install_sequence_from_env(&mut cfg, "release", None));
        assert_eq!(cfg.last_channel_sequence["release"], json!(5));
    }

    #[test]
    fn install_baseline_preserves_existing_sequence() {
        // A machine that already has a recorded baseline (repair / reinstall) must not be reset.
        // The guard returns before any network fetch, so this is also offline-safe in CI.
        let mut cfg = StudioStudConfig {
            channel: "release".into(),
            ..StudioStudConfig::default()
        };
        record_channel_sequence(&mut cfg, Channel::Release, 5);
        record_install_baseline_seq(&mut cfg);
        assert_eq!(cfg.last_channel_sequence["release"], json!(5));
    }

    #[test]
    fn manifest_without_channel_sequence_defaults_zero() {
        let raw = json!({ "daemonVersion": "0.4.0", "pluginVersion": "0.3.7" });
        let m: ChannelManifest = serde_json::from_value(raw).unwrap();
        assert_eq!(m.channel_sequence, 0);
    }

    #[test]
    fn verify_skips_when_signature_absent() {
        // Real-looking embedded key path is irrelevant: absent signature => Ok regardless.
        let raw = json!({
            "daemonVersion": "0.4.0",
            "pluginVersion": "0.3.7",
            "channelSequence": 1
        });
        let m: ChannelManifest = serde_json::from_value(raw.clone()).unwrap();
        assert!(verify_manifest_signature(&raw, &m).is_ok());
    }
}
