use std::time::Duration;

use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const PAGES_BASE: &str = "https://tyleradams2002.github.io/studio-stud";

/// Ed25519 public key (32 bytes hex) embedded at build time from `secrets/channel-signing.pub`.
/// All-zeros = signing disabled (skip verification). Generated by `scripts/keygen.ps1`.
pub const MANIFEST_VERIFY_PUBLIC_KEY_HEX: &str =
    include_str!("../../secrets/channel-signing.pub");

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Channel {
    Release,
    Beta,
    Dev,
}

impl Channel {
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "beta" => Channel::Beta,
            "dev" | "development" => Channel::Dev,
            _ => Channel::Release,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Channel::Release => "release",
            Channel::Beta => "beta",
            Channel::Dev => "dev",
        }
    }

    pub fn manifest_url(self) -> String {
        match self {
            Channel::Release => format!("{PAGES_BASE}/latest.json"),
            Channel::Beta => format!("{PAGES_BASE}/beta/latest.json"),
            Channel::Dev => format!("{PAGES_BASE}/dev/latest.json"),
        }
    }

    pub fn is_encrypted(self) -> bool {
        !matches!(self, Channel::Release)
    }
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelManifest {
    pub daemon_version: String,
    pub plugin_version: String,
    pub protocol_version: Option<i64>,
    pub binary_url: Option<String>,
    pub plugin_url: Option<String>,
    pub setup_url: Option<String>,
    pub setup_enc_url: Option<String>,
    pub channel_sequence: u64,
    pub signature: Option<String>,
    #[serde(default)]
    pub kdf_salt: Option<String>,
    #[serde(default)]
    pub kdf_nonce: Option<String>,
}

pub fn fetch_manifest(channel: Channel) -> Result<(ChannelManifest, Value)> {
    let url = channel.manifest_url();
    let agent: ureq::Agent = ureq::Agent::config_builder()
        .timeout_global(Some(Duration::from_secs(12)))
        .build()
        .into();
    let mut resp = agent.get(&url).call().map_err(|e| anyhow!("{url}: {e}"))?;
    let text = resp
        .body_mut()
        .read_to_string()
        .map_err(|e| anyhow!("read {url}: {e}"))?;
    let raw: Value = serde_json::from_str(&text)?;
    let manifest: ChannelManifest = serde_json::from_value(raw.clone())?;
    Ok((manifest, raw))
}

pub fn verify_manifest_signature(raw: &Value, manifest: &ChannelManifest) -> Result<()> {
    use base64::{Engine as _, engine::general_purpose::STANDARD as B64};
    use ed25519_dalek::{Signature, VerifyingKey, Verifier};

    let key_hex = MANIFEST_VERIFY_PUBLIC_KEY_HEX.trim();
    // All-zeros or placeholder = signing not yet provisioned; skip check.
    if key_hex.chars().all(|c| c == '0') || key_hex.starts_with("PLACEHOLDER") {
        return Ok(());
    }

    let key_bytes = hex_decode_32(key_hex)
        .map_err(|e| anyhow!("bad embedded public key: {e}"))?;
    let verifying_key = VerifyingKey::from_bytes(&key_bytes)
        .map_err(|e| anyhow!("invalid public key: {e}"))?;

    let sig_b64 = manifest
        .signature
        .as_deref()
        .ok_or_else(|| anyhow!("manifest has no signature field"))?;
    let sig_bytes = B64.decode(sig_b64)
        .map_err(|e| anyhow!("bad signature base64: {e}"))?;
    let sig_arr: [u8; 64] = sig_bytes
        .try_into()
        .map_err(|_| anyhow!("signature must be 64 bytes"))?;
    let signature = Signature::from_bytes(&sig_arr);

    // Sign over the canonical manifest JSON without the `signature` field.
    let mut obj = raw.as_object()
        .cloned()
        .ok_or_else(|| anyhow!("manifest is not a JSON object"))?;
    obj.remove("signature");
    let canonical = serde_json::to_string(&Value::Object(obj))?;

    verifying_key
        .verify(canonical.as_bytes(), &signature)
        .map_err(|_| anyhow!("manifest signature verification failed"))
}

fn hex_decode_32(s: &str) -> Result<[u8; 32]> {
    let bytes = (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16))
        .collect::<Result<Vec<u8>, _>>()
        .map_err(|e| anyhow!("hex decode: {e}"))?;
    bytes.try_into().map_err(|_| anyhow!("expected 32 bytes, got {}", s.len() / 2))
}

pub fn check_anti_rollback(
    channel: Channel,
    manifest: &ChannelManifest,
    last_seen: &serde_json::Map<String, Value>,
) -> Result<()> {
    let key = channel.as_str();
    let floor = last_seen
        .get(key)
        .and_then(Value::as_u64)
        .unwrap_or(0);
    if manifest.channel_sequence < floor {
        return Err(anyhow!(
            "manifest channelSequence {} is below floor {}",
            manifest.channel_sequence,
            floor
        ));
    }
    Ok(())
}
